M48
; DRILL file {KiCad 8.0.5} date 2024-10-27T18:20:26+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-27T18:20:26+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0701
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1575
%
G90
G05
T1
X1.2528Y-2.3835
X1.2528Y-3.9835
X1.8528Y-2.3835
X1.8528Y-3.9835
T2
X2.7756Y-1.0606
M30
